### ISSUE TITLE
Como cliente/usuario necesito ingresar al sistema para revisar mi saldo

### ISSUE THREAD

**Issue by Dev626** [HomeBacking/Front#1]

**Comment by Dev626** [comment]
- [x] Validar que los datos ingresados sean corretos
- [x] Maquetar el formulario de inicio de sesion
- [x] Los textos deben estar correctamente escritos

**Comment by Boniich** [comment]
- [x] Cambiar los datos que se ingresan. Ahora son correo electronico y contraseña
- [x] Cambiar las validaciones para que se ajustes a los nuevos datos a ingresar
- [x] Desarrollar la parte responsiva del login

**Comment by Boniich** [comment]
- [x] Arreglar el iconito que muestra o culta la contraseña (se baja al mostrar la contraseña)
